name: Lacework SCA/SAST Pull Request - XPERTS Demo

on: 
  push: 
    branches: 
      - main  # Specify the target branch for the pull request trigger 

jobs: 
  build: 
    runs-on: ubuntu-latest  # The job runs on the latest Ubuntu environment 

    steps: 
      # Step 1: Install the Lacework CLI and SCA component 
      - name: Install Lacework CLI 
        run: | 
          # Download and install the Lacework CLI using a shell script 
          curl https://raw.githubusercontent.com/lacework/go-sdk/main/cli/install.sh | bash 
          # Configure the Lacework CLI with account, API key, and secret from GitHub secrets 
          lacework configure -a ${{ secrets.LW_ACCOUNT }}.lacework.net -k ${{ secrets.LW_API_KEY }} -s ${{ secrets.LW_API_SECRET }} --noninteractive 
          # Install the Software Composition Analysis (SCA) component 
          lacework component install sca 

      # Step 2: Check out the target branch of the pull request 
      - name: Checkout target branch 
        uses: actions/checkout@v3  # Use the checkout action to pull the target branch code 
        with: 
          ref: ${{ github.event.pull_request.base.ref }}  # Reference the target branch of the pull request 
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication 

      # Step 3: Run the Lacework SCA scan on the target branch and save the output 
      - name: Run Lacework SCA Scan on Target Branch 
        run:  lacework sca scan ./ --active-only -f sarif -o /tmp/lacework-scan-target.json 
        # Scan the target branch code, output in SARIF format, and save to /tmp/lacework-scan-target.json 

      # Step 4: Upload the SARIF file for analysis or further use 
      - name: Upload SARIF File 
        uses: actions/upload-artifact@v3  # Use the upload artifact action to save the SARIF file 
        with: 
          name: lacework-comparison-report  # Name of the uploaded artifact 
          path: /tmp/lacework-comparison.sarif  # Path to the SARIF file
